--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 8.0.858
--  Created On : 星期四, 07 六月, 2012 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('custome_group_info') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE custome_group_info
;

CREATE TABLE custome_group_info ( 
	group_id varchar(50) NOT NULL,    -- 主键ID 
	group_name nvarchar(50) NULL,    -- 分组名称 
	status int NULL,    -- 状态 
	created_on datetime NULL,
	created_by nvarchar(50) NULL,
	modified_on datetime NULL,
	modified_by nvarchar(50) NULL,
	status_code int NULL
)
;

ALTER TABLE custome_group_info
	ADD CONSTRAINT UQ_custome_group_info_group_name UNIQUE (status)
;

ALTER TABLE custome_group_info ADD CONSTRAINT PK_custome_group_info 
	PRIMARY KEY CLUSTERED (group_id)
;

EXEC sp_addextendedproperty 'MS_Description', '主键ID', 'Schema', dbo, 'table', custome_group_info, 'column', group_id
;

EXEC sp_addextendedproperty 'MS_Description', '分组名称', 'Schema', dbo, 'table', custome_group_info, 'column', group_name
;

EXEC sp_addextendedproperty 'MS_Description', '状态', 'Schema', dbo, 'table', custome_group_info, 'column', status
;






